### ISSUE TITLE
Screens

### ISSUE THREAD

**Issue by JulianBorghuis** [ThRadio/ThRadio#1]
Can you please give me soms screenshots?? Or a live demo

**Comment by therhenals** [comment]
Hello, screenshots and the web page with the documentation will be available soon.

**Comment by JulianBorghuis** [comment]
> Hello, screenshots and the web page with the documentation will be available soon.

cant you make an quick screen for me?

**Comment by therhenals** [comment]
> > Hello, screenshots and the web page with the documentation will be available soon.
> 
> cant you make an quick screen for me?

![image](https://user-images.githubusercontent.com/30006248/108248231-943fca00-7121-11eb-9c91-a4abc7d8ba61.png)

**Comment by therhenals** [comment]
> > Hello, screenshots and the web page with the documentation will be available soon.
> 
> cant you make an quick screen for me?

Hello, the documentation is now available [here](https://thradio.therhenals.com/) and a new update.
