### ISSUE TITLE
what's next?

### ISSUE THREAD

**Issue by ps-513** [ThRadio/ThRadio#2]
installed everything according to the instructions how to get to the web page?

**Comment by therhenals** [comment]
Hello, the documentation is incomplete and will soon be available on the website.

The first thing to do is to point a DNS record to the ip of the server then you can follow the steps in the README if you enter everything correctly you could access from the domain or subdomain pointed to the ip.

**Comment by ps-513** [comment]
Good evening, I did everything according to the instructions, when connecting to localhost, the site gives an error ERR_SSL_PROTOCOL_ERROR

**Comment by ps-513** [comment]
And do you have to use letsencrypt?
![image](https://user-images.githubusercontent.com/76872504/108259031-19ef6400-717a-11eb-8b60-9dbfbb122c73.png)

**Comment by therhenals** [comment]
> And do you have to use letsencrypt?
> ![image](https://user-images.githubusercontent.com/76872504/108259031-19ef6400-717a-11eb-8b60-9dbfbb122c73.png)

Hello, the documentation is now available [here](https://thradio.therhenals.com/) and a new update.
